version: 2.1
orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    docker:
      - image: cimg/android:2022.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - android-deps-{{ checksum "build.gradle" }}
            - android-deps-

      - run:
          name: Grant Permission to Gradle Wrapper
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: android-deps-{{ checksum "build.gradle" }}

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Lint and Unit Tests
          command: ./gradlew lint testDebugUnitTest

      - store_test_results:
          path: app/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apks

workflows:
  version: 2
  build_and_test:
    jobs:
      - build