version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "core/build.gradle.kts" }}-{{ checksum "favorite/build.gradle.kts" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: android-orb-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}-{{ checksum "core/build.gradle.kts" }}-{{ checksum "favorite/build.gradle.kts" }}
          paths:
            - ~/.gradle
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Build Core Module
          command: ./gradlew :core:assembleRelease
      - run:
          name: Build Favorite Module
          command: ./gradlew :favorite:assembleRelease
      - run:
          name: Build App Module
          command: ./gradlew :app:assembleRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: artifact-file

workflows:
  build_and_test:
    jobs:
      - build
